// HID Keyboard Key Codes
export const HID_KEYBOARD_SC_A = 0x04;
export const HID_KEYBOARD_SC_B = 0x05;
export const HID_KEYBOARD_SC_C = 0x06;
export const HID_KEYBOARD_SC_D = 0x07;
export const HID_KEYBOARD_SC_E = 0x08;
export const HID_KEYBOARD_SC_F = 0x09;
export const HID_KEYBOARD_SC_G = 0x0A;
export const HID_KEYBOARD_SC_H = 0x0B;
export const HID_KEYBOARD_SC_I = 0x0C;
export const HID_KEYBOARD_SC_J = 0x0D;
export const HID_KEYBOARD_SC_K = 0x0E;
export const HID_KEYBOARD_SC_L = 0x0F;
export const HID_KEYBOARD_SC_M = 0x10;
export const HID_KEYBOARD_SC_N = 0x11;
export const HID_KEYBOARD_SC_O = 0x12;
export const HID_KEYBOARD_SC_P = 0x13;
export const HID_KEYBOARD_SC_Q = 0x14;
export const HID_KEYBOARD_SC_R = 0x15;
export const HID_KEYBOARD_SC_S = 0x16;
export const HID_KEYBOARD_SC_T = 0x17;
export const HID_KEYBOARD_SC_U = 0x18;
export const HID_KEYBOARD_SC_V = 0x19;
export const HID_KEYBOARD_SC_W = 0x1A;
export const HID_KEYBOARD_SC_X = 0x1B;
export const HID_KEYBOARD_SC_Y = 0x1C;
export const HID_KEYBOARD_SC_Z = 0x1D;

export const HID_KEYBOARD_SC_1_AND_EXCLAMATION = 0x1E;
export const HID_KEYBOARD_SC_2_AND_AT = 0x1F;
export const HID_KEYBOARD_SC_3_AND_HASHMARK = 0x20;
export const HID_KEYBOARD_SC_4_AND_DOLLAR = 0x21;
export const HID_KEYBOARD_SC_5_AND_PERCENTAGE = 0x22;
export const HID_KEYBOARD_SC_6_AND_CARET = 0x23;
export const HID_KEYBOARD_SC_7_AND_AMPERSAND = 0x24;
export const HID_KEYBOARD_SC_8_AND_ASTERISK = 0x25;
export const HID_KEYBOARD_SC_9_AND_OPENING_PARENTHESIS = 0x26;
export const HID_KEYBOARD_SC_0_AND_CLOSING_PARENTHESIS = 0x27;

export const HID_KEYBOARD_SC_ENTER = 0x28;
export const HID_KEYBOARD_SC_ESCAPE = 0x29;
export const HID_KEYBOARD_SC_BACKSPACE = 0x2A;
export const HID_KEYBOARD_SC_TAB = 0x2B;
export const HID_KEYBOARD_SC_SPACE = 0x2C;
export const HID_KEYBOARD_SC_MINUS_AND_UNDERSCORE = 0x2D;
export const HID_KEYBOARD_SC_EQUAL_AND_PLUS = 0x2E;
export const HID_KEYBOARD_SC_OPENING_BRACKET_AND_OPENING_BRACE = 0x2F;
export const HID_KEYBOARD_SC_CLOSING_BRACKET_AND_CLOSING_BRACE = 0x30;
export const HID_KEYBOARD_SC_BACKSLASH_AND_PIPE = 0x31;
export const HID_KEYBOARD_SC_SEMICOLON_AND_COLON = 0x33;
export const HID_KEYBOARD_SC_APOSTROPHE_AND_QUOTATION_MARK = 0x34;
export const HID_KEYBOARD_SC_GRAVE_ACCENT_AND_TILDE = 0x35;
export const HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN = 0x36;
export const HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN = 0x37;
export const HID_KEYBOARD_SC_SLASH_AND_QUESTION_MARK = 0x38;
export const HID_KEYBOARD_SC_CAPS_LOCK = 0x39;

export const HID_KEYBOARD_SC_F1 = 0x3A;
export const HID_KEYBOARD_SC_F2 = 0x3B;
export const HID_KEYBOARD_SC_F3 = 0x3C;
export const HID_KEYBOARD_SC_F4 = 0x3D;
export const HID_KEYBOARD_SC_F5 = 0x3E;
export const HID_KEYBOARD_SC_F6 = 0x3F;
export const HID_KEYBOARD_SC_F7 = 0x40;
export const HID_KEYBOARD_SC_F8 = 0x41;
export const HID_KEYBOARD_SC_F9 = 0x42;
export const HID_KEYBOARD_SC_F10 = 0x43;
export const HID_KEYBOARD_SC_F11 = 0x44;
export const HID_KEYBOARD_SC_F12 = 0x45;

export const HID_KEYBOARD_SC_PRINT_SCREEN = 0x46;
export const HID_KEYBOARD_SC_SCROLL_LOCK = 0x47;
export const HID_KEYBOARD_SC_PAUSE = 0x48;
export const HID_KEYBOARD_SC_INSERT = 0x49;
export const HID_KEYBOARD_SC_HOME = 0x4A;
export const HID_KEYBOARD_SC_PAGE_UP = 0x4B;
export const HID_KEYBOARD_SC_DELETE = 0x4C;
export const HID_KEYBOARD_SC_END = 0x4D;
export const HID_KEYBOARD_SC_PAGE_DOWN = 0x4E;
export const HID_KEYBOARD_SC_RIGHT_ARROW = 0x4F;
export const HID_KEYBOARD_SC_LEFT_ARROW = 0x50;
export const HID_KEYBOARD_SC_DOWN_ARROW = 0x51;
export const HID_KEYBOARD_SC_UP_ARROW = 0x52;

export const HID_KEYBOARD_SC_NUM_LOCK = 0x53;
export const HID_KEYBOARD_SC_KEYPAD_SLASH = 0x54;
export const HID_KEYBOARD_SC_KEYPAD_ASTERISK = 0x55;
export const HID_KEYBOARD_SC_KEYPAD_MINUS = 0x56;
export const HID_KEYBOARD_SC_KEYPAD_PLUS = 0x57;
export const HID_KEYBOARD_SC_KEYPAD_ENTER = 0x58;
export const HID_KEYBOARD_SC_KEYPAD_1_AND_END = 0x59;
export const HID_KEYBOARD_SC_KEYPAD_2_AND_DOWN_ARROW = 0x5A;
export const HID_KEYBOARD_SC_KEYPAD_3_AND_PAGE_DOWN = 0x5B;
export const HID_KEYBOARD_SC_KEYPAD_4_AND_LEFT_ARROW = 0x5C;
export const HID_KEYBOARD_SC_KEYPAD_5 = 0x5D;
export const HID_KEYBOARD_SC_KEYPAD_6_AND_RIGHT_ARROW = 0x5E;
export const HID_KEYBOARD_SC_KEYPAD_7_AND_HOME = 0x5F;
export const HID_KEYBOARD_SC_KEYPAD_8_AND_UP_ARROW = 0x60;
export const HID_KEYBOARD_SC_KEYPAD_9_AND_PAGE_UP = 0x61;
export const HID_KEYBOARD_SC_KEYPAD_0_AND_INSERT = 0x62;
export const HID_KEYBOARD_SC_KEYPAD_DOT_AND_DELETE = 0x63;

// Key code to name mapping
const keyCodeToName: Record<number, string> = {
  [HID_KEYBOARD_SC_A]: 'A',
  [HID_KEYBOARD_SC_B]: 'B',
  [HID_KEYBOARD_SC_C]: 'C',
  [HID_KEYBOARD_SC_D]: 'D',
  [HID_KEYBOARD_SC_E]: 'E',
  [HID_KEYBOARD_SC_F]: 'F',
  [HID_KEYBOARD_SC_G]: 'G',
  [HID_KEYBOARD_SC_H]: 'H',
  [HID_KEYBOARD_SC_I]: 'I',
  [HID_KEYBOARD_SC_J]: 'J',
  [HID_KEYBOARD_SC_K]: 'K',
  [HID_KEYBOARD_SC_L]: 'L',
  [HID_KEYBOARD_SC_M]: 'M',
  [HID_KEYBOARD_SC_N]: 'N',
  [HID_KEYBOARD_SC_O]: 'O',
  [HID_KEYBOARD_SC_P]: 'P',
  [HID_KEYBOARD_SC_Q]: 'Q',
  [HID_KEYBOARD_SC_R]: 'R',
  [HID_KEYBOARD_SC_S]: 'S',
  [HID_KEYBOARD_SC_T]: 'T',
  [HID_KEYBOARD_SC_U]: 'U',
  [HID_KEYBOARD_SC_V]: 'V',
  [HID_KEYBOARD_SC_W]: 'W',
  [HID_KEYBOARD_SC_X]: 'X',
  [HID_KEYBOARD_SC_Y]: 'Y',
  [HID_KEYBOARD_SC_Z]: 'Z',
  [HID_KEYBOARD_SC_1_AND_EXCLAMATION]: '1',
  [HID_KEYBOARD_SC_2_AND_AT]: '2',
  [HID_KEYBOARD_SC_3_AND_HASHMARK]: '3',
  [HID_KEYBOARD_SC_4_AND_DOLLAR]: '4',
  [HID_KEYBOARD_SC_5_AND_PERCENTAGE]: '5',
  [HID_KEYBOARD_SC_6_AND_CARET]: '6',
  [HID_KEYBOARD_SC_7_AND_AMPERSAND]: '7',
  [HID_KEYBOARD_SC_8_AND_ASTERISK]: '8',
  [HID_KEYBOARD_SC_9_AND_OPENING_PARENTHESIS]: '9',
  [HID_KEYBOARD_SC_0_AND_CLOSING_PARENTHESIS]: '0',
  [HID_KEYBOARD_SC_ENTER]: 'Enter',
  [HID_KEYBOARD_SC_ESCAPE]: 'Esc',
  [HID_KEYBOARD_SC_BACKSPACE]: 'Backspace',
  [HID_KEYBOARD_SC_TAB]: 'Tab',
  [HID_KEYBOARD_SC_SPACE]: 'Space',
  [HID_KEYBOARD_SC_MINUS_AND_UNDERSCORE]: '-',
  [HID_KEYBOARD_SC_EQUAL_AND_PLUS]: '=',
  [HID_KEYBOARD_SC_OPENING_BRACKET_AND_OPENING_BRACE]: '[',
  [HID_KEYBOARD_SC_CLOSING_BRACKET_AND_CLOSING_BRACE]: ']',
  [HID_KEYBOARD_SC_BACKSLASH_AND_PIPE]: '\\',
  [HID_KEYBOARD_SC_SEMICOLON_AND_COLON]: ';',
  [HID_KEYBOARD_SC_APOSTROPHE_AND_QUOTATION_MARK]: "'",
  [HID_KEYBOARD_SC_GRAVE_ACCENT_AND_TILDE]: '`',
  [HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN]: ',',
  [HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN]: '.',
  [HID_KEYBOARD_SC_SLASH_AND_QUESTION_MARK]: '/',
  [HID_KEYBOARD_SC_CAPS_LOCK]: 'Caps Lock',
  [HID_KEYBOARD_SC_F1]: 'F1',
  [HID_KEYBOARD_SC_F2]: 'F2',
  [HID_KEYBOARD_SC_F3]: 'F3',
  [HID_KEYBOARD_SC_F4]: 'F4',
  [HID_KEYBOARD_SC_F5]: 'F5',
  [HID_KEYBOARD_SC_F6]: 'F6',
  [HID_KEYBOARD_SC_F7]: 'F7',
  [HID_KEYBOARD_SC_F8]: 'F8',
  [HID_KEYBOARD_SC_F9]: 'F9',
  [HID_KEYBOARD_SC_F10]: 'F10',
  [HID_KEYBOARD_SC_F11]: 'F11',
  [HID_KEYBOARD_SC_F12]: 'F12',
  [HID_KEYBOARD_SC_PRINT_SCREEN]: 'Print Screen',
  [HID_KEYBOARD_SC_SCROLL_LOCK]: 'Scroll Lock',
  [HID_KEYBOARD_SC_PAUSE]: 'Pause',
  [HID_KEYBOARD_SC_INSERT]: 'Insert',
  [HID_KEYBOARD_SC_HOME]: 'Home',
  [HID_KEYBOARD_SC_PAGE_UP]: 'Page Up',
  [HID_KEYBOARD_SC_DELETE]: 'Delete',
  [HID_KEYBOARD_SC_END]: 'End',
  [HID_KEYBOARD_SC_PAGE_DOWN]: 'Page Down',
  [HID_KEYBOARD_SC_RIGHT_ARROW]: 'Right',
  [HID_KEYBOARD_SC_LEFT_ARROW]: 'Left',
  [HID_KEYBOARD_SC_DOWN_ARROW]: 'Down',
  [HID_KEYBOARD_SC_UP_ARROW]: 'Up',
  [HID_KEYBOARD_SC_NUM_LOCK]: 'Num Lock',
  [HID_KEYBOARD_SC_KEYPAD_SLASH]: 'Keypad /',
  [HID_KEYBOARD_SC_KEYPAD_ASTERISK]: 'Keypad *',
  [HID_KEYBOARD_SC_KEYPAD_MINUS]: 'Keypad -',
  [HID_KEYBOARD_SC_KEYPAD_PLUS]: 'Keypad +',
  [HID_KEYBOARD_SC_KEYPAD_ENTER]: 'Keypad Enter',
  [HID_KEYBOARD_SC_KEYPAD_1_AND_END]: 'Keypad 1',
  [HID_KEYBOARD_SC_KEYPAD_2_AND_DOWN_ARROW]: 'Keypad 2',
  [HID_KEYBOARD_SC_KEYPAD_3_AND_PAGE_DOWN]: 'Keypad 3',
  [HID_KEYBOARD_SC_KEYPAD_4_AND_LEFT_ARROW]: 'Keypad 4',
  [HID_KEYBOARD_SC_KEYPAD_5]: 'Keypad 5',
  [HID_KEYBOARD_SC_KEYPAD_6_AND_RIGHT_ARROW]: 'Keypad 6',
  [HID_KEYBOARD_SC_KEYPAD_7_AND_HOME]: 'Keypad 7',
  [HID_KEYBOARD_SC_KEYPAD_8_AND_UP_ARROW]: 'Keypad 8',
  [HID_KEYBOARD_SC_KEYPAD_9_AND_PAGE_UP]: 'Keypad 9',
  [HID_KEYBOARD_SC_KEYPAD_0_AND_INSERT]: 'Keypad 0',
  [HID_KEYBOARD_SC_KEYPAD_DOT_AND_DELETE]: 'Keypad .'
};

// Key code mapping
const keyCodeToHID: Record<string, number> = {
  'KeyA': HID_KEYBOARD_SC_A,
  'KeyB': HID_KEYBOARD_SC_B,
  'KeyC': HID_KEYBOARD_SC_C,
  'KeyD': HID_KEYBOARD_SC_D,
  'KeyE': HID_KEYBOARD_SC_E,
  'KeyF': HID_KEYBOARD_SC_F,
  'KeyG': HID_KEYBOARD_SC_G,
  'KeyH': HID_KEYBOARD_SC_H,
  'KeyI': HID_KEYBOARD_SC_I,
  'KeyJ': HID_KEYBOARD_SC_J,
  'KeyK': HID_KEYBOARD_SC_K,
  'KeyL': HID_KEYBOARD_SC_L,
  'KeyM': HID_KEYBOARD_SC_M,
  'KeyN': HID_KEYBOARD_SC_N,
  'KeyO': HID_KEYBOARD_SC_O,
  'KeyP': HID_KEYBOARD_SC_P,
  'KeyQ': HID_KEYBOARD_SC_Q,
  'KeyR': HID_KEYBOARD_SC_R,
  'KeyS': HID_KEYBOARD_SC_S,
  'KeyT': HID_KEYBOARD_SC_T,
  'KeyU': HID_KEYBOARD_SC_U,
  'KeyV': HID_KEYBOARD_SC_V,
  'KeyW': HID_KEYBOARD_SC_W,
  'KeyX': HID_KEYBOARD_SC_X,
  'KeyY': HID_KEYBOARD_SC_Y,
  'KeyZ': HID_KEYBOARD_SC_Z,
  'Digit1': HID_KEYBOARD_SC_1_AND_EXCLAMATION,
  'Digit2': HID_KEYBOARD_SC_2_AND_AT,
  'Digit3': HID_KEYBOARD_SC_3_AND_HASHMARK,
  'Digit4': HID_KEYBOARD_SC_4_AND_DOLLAR,
  'Digit5': HID_KEYBOARD_SC_5_AND_PERCENTAGE,
  'Digit6': HID_KEYBOARD_SC_6_AND_CARET,
  'Digit7': HID_KEYBOARD_SC_7_AND_AMPERSAND,
  'Digit8': HID_KEYBOARD_SC_8_AND_ASTERISK,
  'Digit9': HID_KEYBOARD_SC_9_AND_OPENING_PARENTHESIS,
  'Digit0': HID_KEYBOARD_SC_0_AND_CLOSING_PARENTHESIS,
  'Enter': HID_KEYBOARD_SC_ENTER,
  'Escape': HID_KEYBOARD_SC_ESCAPE,
  'Backspace': HID_KEYBOARD_SC_BACKSPACE,
  'Tab': HID_KEYBOARD_SC_TAB,
  'Space': HID_KEYBOARD_SC_SPACE,
  'Minus': HID_KEYBOARD_SC_MINUS_AND_UNDERSCORE,
  'Equal': HID_KEYBOARD_SC_EQUAL_AND_PLUS,
  'BracketLeft': HID_KEYBOARD_SC_OPENING_BRACKET_AND_OPENING_BRACE,
  'BracketRight': HID_KEYBOARD_SC_CLOSING_BRACKET_AND_CLOSING_BRACE,
  'Backslash': HID_KEYBOARD_SC_BACKSLASH_AND_PIPE,
  'Semicolon': HID_KEYBOARD_SC_SEMICOLON_AND_COLON,
  'Quote': HID_KEYBOARD_SC_APOSTROPHE_AND_QUOTATION_MARK,
  'Backquote': HID_KEYBOARD_SC_GRAVE_ACCENT_AND_TILDE,
  'Comma': HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN,
  'Period': HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN,
  'Slash': HID_KEYBOARD_SC_SLASH_AND_QUESTION_MARK,
  'CapsLock': HID_KEYBOARD_SC_CAPS_LOCK,
  'F1': HID_KEYBOARD_SC_F1,
  'F2': HID_KEYBOARD_SC_F2,
  'F3': HID_KEYBOARD_SC_F3,
  'F4': HID_KEYBOARD_SC_F4,
  'F5': HID_KEYBOARD_SC_F5,
  'F6': HID_KEYBOARD_SC_F6,
  'F7': HID_KEYBOARD_SC_F7,
  'F8': HID_KEYBOARD_SC_F8,
  'F9': HID_KEYBOARD_SC_F9,
  'F10': HID_KEYBOARD_SC_F10,
  'F11': HID_KEYBOARD_SC_F11,
  'F12': HID_KEYBOARD_SC_F12,
  'PrintScreen': HID_KEYBOARD_SC_PRINT_SCREEN,
  'ScrollLock': HID_KEYBOARD_SC_SCROLL_LOCK,
  'Pause': HID_KEYBOARD_SC_PAUSE,
  'Insert': HID_KEYBOARD_SC_INSERT,
  'Home': HID_KEYBOARD_SC_HOME,
  'PageUp': HID_KEYBOARD_SC_PAGE_UP,
  'Delete': HID_KEYBOARD_SC_DELETE,
  'End': HID_KEYBOARD_SC_END,
  'PageDown': HID_KEYBOARD_SC_PAGE_DOWN,
  'ArrowRight': HID_KEYBOARD_SC_RIGHT_ARROW,
  'ArrowLeft': HID_KEYBOARD_SC_LEFT_ARROW,
  'ArrowDown': HID_KEYBOARD_SC_DOWN_ARROW,
  'ArrowUp': HID_KEYBOARD_SC_UP_ARROW,
  'NumLock': HID_KEYBOARD_SC_NUM_LOCK,
  'NumpadDivide': HID_KEYBOARD_SC_KEYPAD_SLASH,
  'NumpadMultiply': HID_KEYBOARD_SC_KEYPAD_ASTERISK,
  'NumpadSubtract': HID_KEYBOARD_SC_KEYPAD_MINUS,
  'NumpadAdd': HID_KEYBOARD_SC_KEYPAD_PLUS,
  'NumpadEnter': HID_KEYBOARD_SC_KEYPAD_ENTER,
  'Numpad1': HID_KEYBOARD_SC_KEYPAD_1_AND_END,
  'Numpad2': HID_KEYBOARD_SC_KEYPAD_2_AND_DOWN_ARROW,
  'Numpad3': HID_KEYBOARD_SC_KEYPAD_3_AND_PAGE_DOWN,
  'Numpad4': HID_KEYBOARD_SC_KEYPAD_4_AND_LEFT_ARROW,
  'Numpad5': HID_KEYBOARD_SC_KEYPAD_5,
  'Numpad6': HID_KEYBOARD_SC_KEYPAD_6_AND_RIGHT_ARROW,
  'Numpad7': HID_KEYBOARD_SC_KEYPAD_7_AND_HOME,
  'Numpad8': HID_KEYBOARD_SC_KEYPAD_8_AND_UP_ARROW,
  'Numpad9': HID_KEYBOARD_SC_KEYPAD_9_AND_PAGE_UP,
  'Numpad0': HID_KEYBOARD_SC_KEYPAD_0_AND_INSERT,
  'NumpadDecimal': HID_KEYBOARD_SC_KEYPAD_DOT_AND_DELETE
};

export function getKeyName(keyCode: number): string {
  return keyCodeToName[keyCode] || `Key ${keyCode}`;
}

export function getKeyCode(keyCode: string): number {
  return keyCodeToHID[keyCode] || 0;
}
