// HID Keyboard Key Codes
// Copied from LUFA in LUFA/Drivers/USB/Class/Common/HIDClassCommon.h
export const HID_KEYBOARD_SC_RESERVED = 0x00;
export const HID_KEYBOARD_SC_ERROR_ROLLOVER = 0x01;
export const HID_KEYBOARD_SC_POST_FAIL = 0x02;
export const HID_KEYBOARD_SC_ERROR_UNDEFINED = 0x03;
export const HID_KEYBOARD_SC_A = 0x04;
export const HID_KEYBOARD_SC_B = 0x05;
export const HID_KEYBOARD_SC_C = 0x06;
export const HID_KEYBOARD_SC_D = 0x07;
export const HID_KEYBOARD_SC_E = 0x08;
export const HID_KEYBOARD_SC_F = 0x09;
export const HID_KEYBOARD_SC_G = 0x0A;
export const HID_KEYBOARD_SC_H = 0x0B;
export const HID_KEYBOARD_SC_I = 0x0C;
export const HID_KEYBOARD_SC_J = 0x0D;
export const HID_KEYBOARD_SC_K = 0x0E;
export const HID_KEYBOARD_SC_L = 0x0F;
export const HID_KEYBOARD_SC_M = 0x10;
export const HID_KEYBOARD_SC_N = 0x11;
export const HID_KEYBOARD_SC_O = 0x12;
export const HID_KEYBOARD_SC_P = 0x13;
export const HID_KEYBOARD_SC_Q = 0x14;
export const HID_KEYBOARD_SC_R = 0x15;
export const HID_KEYBOARD_SC_S = 0x16;
export const HID_KEYBOARD_SC_T = 0x17;
export const HID_KEYBOARD_SC_U = 0x18;
export const HID_KEYBOARD_SC_V = 0x19;
export const HID_KEYBOARD_SC_W = 0x1A;
export const HID_KEYBOARD_SC_X = 0x1B;
export const HID_KEYBOARD_SC_Y = 0x1C;
export const HID_KEYBOARD_SC_Z = 0x1D;
export const HID_KEYBOARD_SC_1_AND_EXCLAMATION = 0x1E;
export const HID_KEYBOARD_SC_2_AND_AT = 0x1F;
export const HID_KEYBOARD_SC_3_AND_HASHMARK = 0x20;
export const HID_KEYBOARD_SC_4_AND_DOLLAR = 0x21;
export const HID_KEYBOARD_SC_5_AND_PERCENTAGE = 0x22;
export const HID_KEYBOARD_SC_6_AND_CARET = 0x23;
export const HID_KEYBOARD_SC_7_AND_AMPERSAND = 0x24;
export const HID_KEYBOARD_SC_8_AND_ASTERISK = 0x25;
export const HID_KEYBOARD_SC_9_AND_OPENING_PARENTHESIS = 0x26;
export const HID_KEYBOARD_SC_0_AND_CLOSING_PARENTHESIS = 0x27;
export const HID_KEYBOARD_SC_ENTER = 0x28;
export const HID_KEYBOARD_SC_ESCAPE = 0x29;
export const HID_KEYBOARD_SC_BACKSPACE = 0x2A;
export const HID_KEYBOARD_SC_TAB = 0x2B;
export const HID_KEYBOARD_SC_SPACE = 0x2C;
export const HID_KEYBOARD_SC_MINUS_AND_UNDERSCORE = 0x2D;
export const HID_KEYBOARD_SC_EQUAL_AND_PLUS = 0x2E;
export const HID_KEYBOARD_SC_OPENING_BRACKET_AND_OPENING_BRACE = 0x2F;
export const HID_KEYBOARD_SC_CLOSING_BRACKET_AND_CLOSING_BRACE = 0x30;
export const HID_KEYBOARD_SC_BACKSLASH_AND_PIPE = 0x31;
export const HID_KEYBOARD_SC_NON_US_HASHMARK_AND_TILDE = 0x32;
export const HID_KEYBOARD_SC_SEMICOLON_AND_COLON = 0x33;
export const HID_KEYBOARD_SC_APOSTROPHE_AND_QUOTE = 0x34;
export const HID_KEYBOARD_SC_GRAVE_ACCENT_AND_TILDE = 0x35;
export const HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN = 0x36;
export const HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN = 0x37;
export const HID_KEYBOARD_SC_SLASH_AND_QUESTION_MARK = 0x38;
export const HID_KEYBOARD_SC_CAPS_LOCK = 0x39;
export const HID_KEYBOARD_SC_F1 = 0x3A;
export const HID_KEYBOARD_SC_F2 = 0x3B;
export const HID_KEYBOARD_SC_F3 = 0x3C;
export const HID_KEYBOARD_SC_F4 = 0x3D;
export const HID_KEYBOARD_SC_F5 = 0x3E;
export const HID_KEYBOARD_SC_F6 = 0x3F;
export const HID_KEYBOARD_SC_F7 = 0x40;
export const HID_KEYBOARD_SC_F8 = 0x41;
export const HID_KEYBOARD_SC_F9 = 0x42;
export const HID_KEYBOARD_SC_F10 = 0x43;
export const HID_KEYBOARD_SC_F11 = 0x44;
export const HID_KEYBOARD_SC_F12 = 0x45;
export const HID_KEYBOARD_SC_PRINT_SCREEN = 0x46;
export const HID_KEYBOARD_SC_SCROLL_LOCK = 0x47;
export const HID_KEYBOARD_SC_PAUSE = 0x48;
export const HID_KEYBOARD_SC_INSERT = 0x49;
export const HID_KEYBOARD_SC_HOME = 0x4A;
export const HID_KEYBOARD_SC_PAGE_UP = 0x4B;
export const HID_KEYBOARD_SC_DELETE = 0x4C;
export const HID_KEYBOARD_SC_END = 0x4D;
export const HID_KEYBOARD_SC_PAGE_DOWN = 0x4E;
export const HID_KEYBOARD_SC_RIGHT_ARROW = 0x4F;
export const HID_KEYBOARD_SC_LEFT_ARROW = 0x50;
export const HID_KEYBOARD_SC_DOWN_ARROW = 0x51;
export const HID_KEYBOARD_SC_UP_ARROW = 0x52;
export const HID_KEYBOARD_SC_NUM_LOCK = 0x53;
export const HID_KEYBOARD_SC_KEYPAD_SLASH = 0x54;
export const HID_KEYBOARD_SC_KEYPAD_ASTERISK = 0x55;
export const HID_KEYBOARD_SC_KEYPAD_MINUS = 0x56;
export const HID_KEYBOARD_SC_KEYPAD_PLUS = 0x57;
export const HID_KEYBOARD_SC_KEYPAD_ENTER = 0x58;
export const HID_KEYBOARD_SC_KEYPAD_1_AND_END = 0x59;
export const HID_KEYBOARD_SC_KEYPAD_2_AND_DOWN_ARROW = 0x5A;
export const HID_KEYBOARD_SC_KEYPAD_3_AND_PAGE_DOWN = 0x5B;
export const HID_KEYBOARD_SC_KEYPAD_4_AND_LEFT_ARROW = 0x5C;
export const HID_KEYBOARD_SC_KEYPAD_5 = 0x5D;
export const HID_KEYBOARD_SC_KEYPAD_6_AND_RIGHT_ARROW = 0x5E;
export const HID_KEYBOARD_SC_KEYPAD_7_AND_HOME = 0x5F;
export const HID_KEYBOARD_SC_KEYPAD_8_AND_UP_ARROW = 0x60;
export const HID_KEYBOARD_SC_KEYPAD_9_AND_PAGE_UP = 0x61;
export const HID_KEYBOARD_SC_KEYPAD_0_AND_INSERT = 0x62;
export const HID_KEYBOARD_SC_KEYPAD_DOT_AND_DELETE = 0x63;
export const HID_KEYBOARD_SC_NON_US_BACKSLASH_AND_PIPE = 0x64;
export const HID_KEYBOARD_SC_APPLICATION = 0x65;
export const HID_KEYBOARD_SC_POWER = 0x66;
export const HID_KEYBOARD_SC_KEYPAD_EQUAL_SIGN = 0x67;
export const HID_KEYBOARD_SC_F13 = 0x68;
export const HID_KEYBOARD_SC_F14 = 0x69;
export const HID_KEYBOARD_SC_F15 = 0x6A;
export const HID_KEYBOARD_SC_F16 = 0x6B;
export const HID_KEYBOARD_SC_F17 = 0x6C;
export const HID_KEYBOARD_SC_F18 = 0x6D;
export const HID_KEYBOARD_SC_F19 = 0x6E;
export const HID_KEYBOARD_SC_F20 = 0x6F;
export const HID_KEYBOARD_SC_F21 = 0x70;
export const HID_KEYBOARD_SC_F22 = 0x71;
export const HID_KEYBOARD_SC_F23 = 0x72;
export const HID_KEYBOARD_SC_F24 = 0x73;
export const HID_KEYBOARD_SC_EXECUTE = 0x74;
export const HID_KEYBOARD_SC_HELP = 0x75;
export const HID_KEYBOARD_SC_MENU = 0x76;
export const HID_KEYBOARD_SC_SELECT = 0x77;
export const HID_KEYBOARD_SC_STOP = 0x78;
export const HID_KEYBOARD_SC_AGAIN = 0x79;
export const HID_KEYBOARD_SC_UNDO = 0x7A;
export const HID_KEYBOARD_SC_CUT = 0x7B;
export const HID_KEYBOARD_SC_COPY = 0x7C;
export const HID_KEYBOARD_SC_PASTE = 0x7D;
export const HID_KEYBOARD_SC_FIND = 0x7E;
export const HID_KEYBOARD_SC_MUTE = 0x7F;
export const HID_KEYBOARD_SC_VOLUME_UP = 0x80;
export const HID_KEYBOARD_SC_VOLUME_DOWN = 0x81;
export const HID_KEYBOARD_SC_LOCKING_CAPS_LOCK = 0x82;
export const HID_KEYBOARD_SC_LOCKING_NUM_LOCK = 0x83;
export const HID_KEYBOARD_SC_LOCKING_SCROLL_LOCK = 0x84;
export const HID_KEYBOARD_SC_KEYPAD_COMMA = 0x85;
export const HID_KEYBOARD_SC_KEYPAD_EQUAL_SIGN_AS400 = 0x86;
export const HID_KEYBOARD_SC_INTERNATIONAL1 = 0x87;
export const HID_KEYBOARD_SC_INTERNATIONAL2 = 0x88;
export const HID_KEYBOARD_SC_INTERNATIONAL3 = 0x89;
export const HID_KEYBOARD_SC_INTERNATIONAL4 = 0x8A;
export const HID_KEYBOARD_SC_INTERNATIONAL5 = 0x8B;
export const HID_KEYBOARD_SC_INTERNATIONAL6 = 0x8C;
export const HID_KEYBOARD_SC_INTERNATIONAL7 = 0x8D;
export const HID_KEYBOARD_SC_INTERNATIONAL8 = 0x8E;
export const HID_KEYBOARD_SC_INTERNATIONAL9 = 0x8F;
export const HID_KEYBOARD_SC_LANG1 = 0x90;
export const HID_KEYBOARD_SC_LANG2 = 0x91;
export const HID_KEYBOARD_SC_LANG3 = 0x92;
export const HID_KEYBOARD_SC_LANG4 = 0x93;
export const HID_KEYBOARD_SC_LANG5 = 0x94;
export const HID_KEYBOARD_SC_LANG6 = 0x95;
export const HID_KEYBOARD_SC_LANG7 = 0x96;
export const HID_KEYBOARD_SC_LANG8 = 0x97;
export const HID_KEYBOARD_SC_LANG9 = 0x98;
export const HID_KEYBOARD_SC_ALTERNATE_ERASE = 0x99;
export const HID_KEYBOARD_SC_SYSREQ = 0x9A;
export const HID_KEYBOARD_SC_CANCEL = 0x9B;
export const HID_KEYBOARD_SC_CLEAR = 0x9C;
export const HID_KEYBOARD_SC_PRIOR = 0x9D;
export const HID_KEYBOARD_SC_RETURN = 0x9E;
export const HID_KEYBOARD_SC_SEPARATOR = 0x9F;
export const HID_KEYBOARD_SC_OUT = 0xA0;
export const HID_KEYBOARD_SC_OPER = 0xA1;
export const HID_KEYBOARD_SC_CLEAR_AND_AGAIN = 0xA2;
export const HID_KEYBOARD_SC_CRSEL_AND_PROPS = 0xA3;
export const HID_KEYBOARD_SC_EXSEL = 0xA4;
export const HID_KEYBOARD_SC_KEYPAD_00 = 0xB0;
export const HID_KEYBOARD_SC_KEYPAD_000 = 0xB1;
export const HID_KEYBOARD_SC_THOUSANDS_SEPARATOR = 0xB2;
export const HID_KEYBOARD_SC_DECIMAL_SEPARATOR = 0xB3;
export const HID_KEYBOARD_SC_CURRENCY_UNIT = 0xB4;
export const HID_KEYBOARD_SC_CURRENCY_SUB_UNIT = 0xB5;
export const HID_KEYBOARD_SC_KEYPAD_OPENING_PARENTHESIS = 0xB6;
export const HID_KEYBOARD_SC_KEYPAD_CLOSING_PARENTHESIS = 0xB7;
export const HID_KEYBOARD_SC_KEYPAD_OPENING_BRACE = 0xB8;
export const HID_KEYBOARD_SC_KEYPAD_CLOSING_BRACE = 0xB9;
export const HID_KEYBOARD_SC_KEYPAD_TAB = 0xBA;
export const HID_KEYBOARD_SC_KEYPAD_BACKSPACE = 0xBB;
export const HID_KEYBOARD_SC_KEYPAD_A = 0xBC;
export const HID_KEYBOARD_SC_KEYPAD_B = 0xBD;
export const HID_KEYBOARD_SC_KEYPAD_C = 0xBE;
export const HID_KEYBOARD_SC_KEYPAD_D = 0xBF;
export const HID_KEYBOARD_SC_KEYPAD_E = 0xC0;
export const HID_KEYBOARD_SC_KEYPAD_F = 0xC1;
export const HID_KEYBOARD_SC_KEYPAD_XOR = 0xC2;
export const HID_KEYBOARD_SC_KEYPAD_CARET = 0xC3;
export const HID_KEYBOARD_SC_KEYPAD_PERCENTAGE = 0xC4;
export const HID_KEYBOARD_SC_KEYPAD_LESS_THAN_SIGN = 0xC5;
export const HID_KEYBOARD_SC_KEYPAD_GREATER_THAN_SIGN = 0xC6;
export const HID_KEYBOARD_SC_KEYPAD_AMP = 0xC7;
export const HID_KEYBOARD_SC_KEYPAD_AMP_AMP = 0xC8;
export const HID_KEYBOARD_SC_KEYPAD_PIPE = 0xC9;
export const HID_KEYBOARD_SC_KEYPAD_PIPE_PIPE = 0xCA;
export const HID_KEYBOARD_SC_KEYPAD_COLON = 0xCB;
export const HID_KEYBOARD_SC_KEYPAD_HASHMARK = 0xCC;
export const HID_KEYBOARD_SC_KEYPAD_SPACE = 0xCD;
export const HID_KEYBOARD_SC_KEYPAD_AT = 0xCE;
export const HID_KEYBOARD_SC_KEYPAD_EXCLAMATION_SIGN = 0xCF;
export const HID_KEYBOARD_SC_KEYPAD_MEMORY_STORE = 0xD0;
export const HID_KEYBOARD_SC_KEYPAD_MEMORY_RECALL = 0xD1;
export const HID_KEYBOARD_SC_KEYPAD_MEMORY_CLEAR = 0xD2;
export const HID_KEYBOARD_SC_KEYPAD_MEMORY_ADD = 0xD3;
export const HID_KEYBOARD_SC_KEYPAD_MEMORY_SUBTRACT = 0xD4;
export const HID_KEYBOARD_SC_KEYPAD_MEMORY_MULTIPLY = 0xD5;
export const HID_KEYBOARD_SC_KEYPAD_MEMORY_DIVIDE = 0xD6;
export const HID_KEYBOARD_SC_KEYPAD_PLUS_AND_MINUS = 0xD7;
export const HID_KEYBOARD_SC_KEYPAD_CLEAR = 0xD8;
export const HID_KEYBOARD_SC_KEYPAD_CLEAR_ENTRY = 0xD9;
export const HID_KEYBOARD_SC_KEYPAD_BINARY = 0xDA;
export const HID_KEYBOARD_SC_KEYPAD_OCTAL = 0xDB;
export const HID_KEYBOARD_SC_KEYPAD_DECIMAL = 0xDC;
export const HID_KEYBOARD_SC_KEYPAD_HEXADECIMAL = 0xDD;
export const HID_KEYBOARD_SC_LEFT_CONTROL = 0xE0;
export const HID_KEYBOARD_SC_LEFT_SHIFT = 0xE1;
export const HID_KEYBOARD_SC_LEFT_ALT = 0xE2;
export const HID_KEYBOARD_SC_LEFT_GUI = 0xE3;
export const HID_KEYBOARD_SC_RIGHT_CONTROL = 0xE4;
export const HID_KEYBOARD_SC_RIGHT_SHIFT = 0xE5;
export const HID_KEYBOARD_SC_RIGHT_ALT = 0xE6;
export const HID_KEYBOARD_SC_RIGHT_GUI = 0xE7;
export const HID_KEYBOARD_SC_MEDIA_PLAY = 0xE8;
export const HID_KEYBOARD_SC_MEDIA_STOP = 0xE9;
export const HID_KEYBOARD_SC_MEDIA_PREVIOUS_TRACK = 0xEA;
export const HID_KEYBOARD_SC_MEDIA_NEXT_TRACK = 0xEB;
export const HID_KEYBOARD_SC_MEDIA_EJECT = 0xEC;
export const HID_KEYBOARD_SC_MEDIA_VOLUME_UP = 0xED;
export const HID_KEYBOARD_SC_MEDIA_VOLUME_DOWN = 0xEE;
export const HID_KEYBOARD_SC_MEDIA_MUTE = 0xEF;
export const HID_KEYBOARD_SC_MEDIA_WWW = 0xF0;
export const HID_KEYBOARD_SC_MEDIA_BACKWARD = 0xF1;
export const HID_KEYBOARD_SC_MEDIA_FORWARD = 0xF2;
export const HID_KEYBOARD_SC_MEDIA_CANCEL = 0xF3;
export const HID_KEYBOARD_SC_MEDIA_SEARCH = 0xF4;
export const HID_KEYBOARD_SC_MEDIA_SLEEP = 0xF8;
export const HID_KEYBOARD_SC_MEDIA_LOCK = 0xF9;
export const HID_KEYBOARD_SC_MEDIA_RELOAD = 0xFA;
export const HID_KEYBOARD_SC_MEDIA_CALCULATOR = 0xFB;

// Key code to name mapping
const keyCodeToName: Record<number, string> = {
  [HID_KEYBOARD_SC_A]: 'A',
  [HID_KEYBOARD_SC_B]: 'B',
  [HID_KEYBOARD_SC_C]: 'C',
  [HID_KEYBOARD_SC_D]: 'D',
  [HID_KEYBOARD_SC_E]: 'E',
  [HID_KEYBOARD_SC_F]: 'F',
  [HID_KEYBOARD_SC_G]: 'G',
  [HID_KEYBOARD_SC_H]: 'H',
  [HID_KEYBOARD_SC_I]: 'I',
  [HID_KEYBOARD_SC_J]: 'J',
  [HID_KEYBOARD_SC_K]: 'K',
  [HID_KEYBOARD_SC_L]: 'L',
  [HID_KEYBOARD_SC_M]: 'M',
  [HID_KEYBOARD_SC_N]: 'N',
  [HID_KEYBOARD_SC_O]: 'O',
  [HID_KEYBOARD_SC_P]: 'P',
  [HID_KEYBOARD_SC_Q]: 'Q',
  [HID_KEYBOARD_SC_R]: 'R',
  [HID_KEYBOARD_SC_S]: 'S',
  [HID_KEYBOARD_SC_T]: 'T',
  [HID_KEYBOARD_SC_U]: 'U',
  [HID_KEYBOARD_SC_V]: 'V',
  [HID_KEYBOARD_SC_W]: 'W',
  [HID_KEYBOARD_SC_X]: 'X',
  [HID_KEYBOARD_SC_Y]: 'Y',
  [HID_KEYBOARD_SC_Z]: 'Z',
  [HID_KEYBOARD_SC_1_AND_EXCLAMATION]: '1',
  [HID_KEYBOARD_SC_2_AND_AT]: '2',
  [HID_KEYBOARD_SC_3_AND_HASHMARK]: '3',
  [HID_KEYBOARD_SC_4_AND_DOLLAR]: '4',
  [HID_KEYBOARD_SC_5_AND_PERCENTAGE]: '5',
  [HID_KEYBOARD_SC_6_AND_CARET]: '6',
  [HID_KEYBOARD_SC_7_AND_AMPERSAND]: '7',
  [HID_KEYBOARD_SC_8_AND_ASTERISK]: '8',
  [HID_KEYBOARD_SC_9_AND_OPENING_PARENTHESIS]: '9',
  [HID_KEYBOARD_SC_0_AND_CLOSING_PARENTHESIS]: '0',
  [HID_KEYBOARD_SC_ENTER]: 'Enter',
  [HID_KEYBOARD_SC_ESCAPE]: 'Esc',
  [HID_KEYBOARD_SC_BACKSPACE]: 'Backspace',
  [HID_KEYBOARD_SC_TAB]: 'Tab',
  [HID_KEYBOARD_SC_SPACE]: 'Space',
  [HID_KEYBOARD_SC_MINUS_AND_UNDERSCORE]: '-',
  [HID_KEYBOARD_SC_EQUAL_AND_PLUS]: '=',
  [HID_KEYBOARD_SC_OPENING_BRACKET_AND_OPENING_BRACE]: '[',
  [HID_KEYBOARD_SC_CLOSING_BRACKET_AND_CLOSING_BRACE]: ']',
  [HID_KEYBOARD_SC_BACKSLASH_AND_PIPE]: '\\',
  [HID_KEYBOARD_SC_SEMICOLON_AND_COLON]: ';',
  [HID_KEYBOARD_SC_APOSTROPHE_AND_QUOTE]: "'",
  [HID_KEYBOARD_SC_GRAVE_ACCENT_AND_TILDE]: '`',
  [HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN]: ',',
  [HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN]: '.',
  [HID_KEYBOARD_SC_SLASH_AND_QUESTION_MARK]: '/',
  [HID_KEYBOARD_SC_CAPS_LOCK]: 'Caps Lock',
  [HID_KEYBOARD_SC_F1]: 'F1',
  [HID_KEYBOARD_SC_F2]: 'F2',
  [HID_KEYBOARD_SC_F3]: 'F3',
  [HID_KEYBOARD_SC_F4]: 'F4',
  [HID_KEYBOARD_SC_F5]: 'F5',
  [HID_KEYBOARD_SC_F6]: 'F6',
  [HID_KEYBOARD_SC_F7]: 'F7',
  [HID_KEYBOARD_SC_F8]: 'F8',
  [HID_KEYBOARD_SC_F9]: 'F9',
  [HID_KEYBOARD_SC_F10]: 'F10',
  [HID_KEYBOARD_SC_F11]: 'F11',
  [HID_KEYBOARD_SC_F12]: 'F12',
  [HID_KEYBOARD_SC_PRINT_SCREEN]: 'Print Screen',
  [HID_KEYBOARD_SC_SCROLL_LOCK]: 'Scroll Lock',
  [HID_KEYBOARD_SC_PAUSE]: 'Pause',
  [HID_KEYBOARD_SC_INSERT]: 'Insert',
  [HID_KEYBOARD_SC_HOME]: 'Home',
  [HID_KEYBOARD_SC_PAGE_UP]: 'Page Up',
  [HID_KEYBOARD_SC_DELETE]: 'Delete',
  [HID_KEYBOARD_SC_END]: 'End',
  [HID_KEYBOARD_SC_PAGE_DOWN]: 'Page Down',
  [HID_KEYBOARD_SC_RIGHT_ARROW]: 'Right',
  [HID_KEYBOARD_SC_LEFT_ARROW]: 'Left',
  [HID_KEYBOARD_SC_DOWN_ARROW]: 'Down',
  [HID_KEYBOARD_SC_UP_ARROW]: 'Up',
  [HID_KEYBOARD_SC_NUM_LOCK]: 'Num Lock',
  [HID_KEYBOARD_SC_KEYPAD_SLASH]: 'Keypad /',
  [HID_KEYBOARD_SC_KEYPAD_ASTERISK]: 'Keypad *',
  [HID_KEYBOARD_SC_KEYPAD_MINUS]: 'Keypad -',
  [HID_KEYBOARD_SC_KEYPAD_PLUS]: 'Keypad +',
  [HID_KEYBOARD_SC_KEYPAD_ENTER]: 'Keypad Enter',
  [HID_KEYBOARD_SC_KEYPAD_1_AND_END]: 'Keypad 1',
  [HID_KEYBOARD_SC_KEYPAD_2_AND_DOWN_ARROW]: 'Keypad 2',
  [HID_KEYBOARD_SC_KEYPAD_3_AND_PAGE_DOWN]: 'Keypad 3',
  [HID_KEYBOARD_SC_KEYPAD_4_AND_LEFT_ARROW]: 'Keypad 4',
  [HID_KEYBOARD_SC_KEYPAD_5]: 'Keypad 5',
  [HID_KEYBOARD_SC_KEYPAD_6_AND_RIGHT_ARROW]: 'Keypad 6',
  [HID_KEYBOARD_SC_KEYPAD_7_AND_HOME]: 'Keypad 7',
  [HID_KEYBOARD_SC_KEYPAD_8_AND_UP_ARROW]: 'Keypad 8',
  [HID_KEYBOARD_SC_KEYPAD_9_AND_PAGE_UP]: 'Keypad 9',
  [HID_KEYBOARD_SC_KEYPAD_0_AND_INSERT]: 'Keypad 0',
  [HID_KEYBOARD_SC_KEYPAD_DOT_AND_DELETE]: 'Keypad .',
  [HID_KEYBOARD_SC_LEFT_CONTROL]: 'Left Control',
  [HID_KEYBOARD_SC_LEFT_SHIFT]: 'Left Shift',
  [HID_KEYBOARD_SC_LEFT_ALT]: 'Left Alt',
  [HID_KEYBOARD_SC_RIGHT_CONTROL]: 'Right Control',
  [HID_KEYBOARD_SC_RIGHT_SHIFT]: 'Right Shift',
  [HID_KEYBOARD_SC_RIGHT_ALT]: 'Right Alt',
};

// Key code mapping
const keyCodeToHID: Record<string, number> = {
  'KeyA': HID_KEYBOARD_SC_A,
  'KeyB': HID_KEYBOARD_SC_B,
  'KeyC': HID_KEYBOARD_SC_C,
  'KeyD': HID_KEYBOARD_SC_D,
  'KeyE': HID_KEYBOARD_SC_E,
  'KeyF': HID_KEYBOARD_SC_F,
  'KeyG': HID_KEYBOARD_SC_G,
  'KeyH': HID_KEYBOARD_SC_H,
  'KeyI': HID_KEYBOARD_SC_I,
  'KeyJ': HID_KEYBOARD_SC_J,
  'KeyK': HID_KEYBOARD_SC_K,
  'KeyL': HID_KEYBOARD_SC_L,
  'KeyM': HID_KEYBOARD_SC_M,
  'KeyN': HID_KEYBOARD_SC_N,
  'KeyO': HID_KEYBOARD_SC_O,
  'KeyP': HID_KEYBOARD_SC_P,
  'KeyQ': HID_KEYBOARD_SC_Q,
  'KeyR': HID_KEYBOARD_SC_R,
  'KeyS': HID_KEYBOARD_SC_S,
  'KeyT': HID_KEYBOARD_SC_T,
  'KeyU': HID_KEYBOARD_SC_U,
  'KeyV': HID_KEYBOARD_SC_V,
  'KeyW': HID_KEYBOARD_SC_W,
  'KeyX': HID_KEYBOARD_SC_X,
  'KeyY': HID_KEYBOARD_SC_Y,
  'KeyZ': HID_KEYBOARD_SC_Z,
  'Digit1': HID_KEYBOARD_SC_1_AND_EXCLAMATION,
  'Digit2': HID_KEYBOARD_SC_2_AND_AT,
  'Digit3': HID_KEYBOARD_SC_3_AND_HASHMARK,
  'Digit4': HID_KEYBOARD_SC_4_AND_DOLLAR,
  'Digit5': HID_KEYBOARD_SC_5_AND_PERCENTAGE,
  'Digit6': HID_KEYBOARD_SC_6_AND_CARET,
  'Digit7': HID_KEYBOARD_SC_7_AND_AMPERSAND,
  'Digit8': HID_KEYBOARD_SC_8_AND_ASTERISK,
  'Digit9': HID_KEYBOARD_SC_9_AND_OPENING_PARENTHESIS,
  'Digit0': HID_KEYBOARD_SC_0_AND_CLOSING_PARENTHESIS,
  'Enter': HID_KEYBOARD_SC_ENTER,
  'Escape': HID_KEYBOARD_SC_ESCAPE,
  'Backspace': HID_KEYBOARD_SC_BACKSPACE,
  'Tab': HID_KEYBOARD_SC_TAB,
  'Space': HID_KEYBOARD_SC_SPACE,
  'Minus': HID_KEYBOARD_SC_MINUS_AND_UNDERSCORE,
  'Equal': HID_KEYBOARD_SC_EQUAL_AND_PLUS,
  'BracketLeft': HID_KEYBOARD_SC_OPENING_BRACKET_AND_OPENING_BRACE,
  'BracketRight': HID_KEYBOARD_SC_CLOSING_BRACKET_AND_CLOSING_BRACE,
  'Backslash': HID_KEYBOARD_SC_BACKSLASH_AND_PIPE,
  'Semicolon': HID_KEYBOARD_SC_SEMICOLON_AND_COLON,
  'Quote': HID_KEYBOARD_SC_APOSTROPHE_AND_QUOTE,
  'Backquote': HID_KEYBOARD_SC_GRAVE_ACCENT_AND_TILDE,
  'Comma': HID_KEYBOARD_SC_COMMA_AND_LESS_THAN_SIGN,
  'Period': HID_KEYBOARD_SC_DOT_AND_GREATER_THAN_SIGN,
  'Slash': HID_KEYBOARD_SC_SLASH_AND_QUESTION_MARK,
  'CapsLock': HID_KEYBOARD_SC_CAPS_LOCK,
  'F1': HID_KEYBOARD_SC_F1,
  'F2': HID_KEYBOARD_SC_F2,
  'F3': HID_KEYBOARD_SC_F3,
  'F4': HID_KEYBOARD_SC_F4,
  'F5': HID_KEYBOARD_SC_F5,
  'F6': HID_KEYBOARD_SC_F6,
  'F7': HID_KEYBOARD_SC_F7,
  'F8': HID_KEYBOARD_SC_F8,
  'F9': HID_KEYBOARD_SC_F9,
  'F10': HID_KEYBOARD_SC_F10,
  'F11': HID_KEYBOARD_SC_F11,
  'F12': HID_KEYBOARD_SC_F12,
  'PrintScreen': HID_KEYBOARD_SC_PRINT_SCREEN,
  'ScrollLock': HID_KEYBOARD_SC_SCROLL_LOCK,
  'Pause': HID_KEYBOARD_SC_PAUSE,
  'Insert': HID_KEYBOARD_SC_INSERT,
  'Home': HID_KEYBOARD_SC_HOME,
  'PageUp': HID_KEYBOARD_SC_PAGE_UP,
  'Delete': HID_KEYBOARD_SC_DELETE,
  'End': HID_KEYBOARD_SC_END,
  'PageDown': HID_KEYBOARD_SC_PAGE_DOWN,
  'ArrowRight': HID_KEYBOARD_SC_RIGHT_ARROW,
  'ArrowLeft': HID_KEYBOARD_SC_LEFT_ARROW,
  'ArrowDown': HID_KEYBOARD_SC_DOWN_ARROW,
  'ArrowUp': HID_KEYBOARD_SC_UP_ARROW,
  'NumLock': HID_KEYBOARD_SC_NUM_LOCK,
  'NumpadDivide': HID_KEYBOARD_SC_KEYPAD_SLASH,
  'NumpadMultiply': HID_KEYBOARD_SC_KEYPAD_ASTERISK,
  'NumpadSubtract': HID_KEYBOARD_SC_KEYPAD_MINUS,
  'NumpadAdd': HID_KEYBOARD_SC_KEYPAD_PLUS,
  'NumpadEnter': HID_KEYBOARD_SC_KEYPAD_ENTER,
  'Numpad1': HID_KEYBOARD_SC_KEYPAD_1_AND_END,
  'Numpad2': HID_KEYBOARD_SC_KEYPAD_2_AND_DOWN_ARROW,
  'Numpad3': HID_KEYBOARD_SC_KEYPAD_3_AND_PAGE_DOWN,
  'Numpad4': HID_KEYBOARD_SC_KEYPAD_4_AND_LEFT_ARROW,
  'Numpad5': HID_KEYBOARD_SC_KEYPAD_5,
  'Numpad6': HID_KEYBOARD_SC_KEYPAD_6_AND_RIGHT_ARROW,
  'Numpad7': HID_KEYBOARD_SC_KEYPAD_7_AND_HOME,
  'Numpad8': HID_KEYBOARD_SC_KEYPAD_8_AND_UP_ARROW,
  'Numpad9': HID_KEYBOARD_SC_KEYPAD_9_AND_PAGE_UP,
  'Numpad0': HID_KEYBOARD_SC_KEYPAD_0_AND_INSERT,
  'NumpadDecimal': HID_KEYBOARD_SC_KEYPAD_DOT_AND_DELETE,
  'ControlLeft': HID_KEYBOARD_SC_LEFT_CONTROL,
  'ShiftLeft': HID_KEYBOARD_SC_LEFT_SHIFT,
  'AltLeft': HID_KEYBOARD_SC_LEFT_ALT,
  'ControlRight': HID_KEYBOARD_SC_RIGHT_CONTROL,
  'ShiftRight': HID_KEYBOARD_SC_RIGHT_SHIFT,
  'AltRight': HID_KEYBOARD_SC_RIGHT_ALT,
};

export function getKeyName(keyCode: number): string {
  return keyCodeToName[keyCode] || `Key ${keyCode}`;
}

export function getKeyCode(keyCode: string): number {
  return keyCodeToHID[keyCode] || 0;
}
