on: [push, pull_request]
name: Continuous Integration
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fw-ci:
    name: Build Firmware
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./fw
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install avr-gcc
        run: |
          curl -L -o /tmp/avr-gcc-14.1.0-x64-linux.tar.bz2 https://github.com/ZakKemble/avr-gcc-build/releases/download/v14.1.0-1/avr-gcc-14.1.0-x64-linux.tar.bz2
          echo Extracting avr-gcc archive
          tar xf /tmp/avr-gcc-14.1.0-x64-linux.tar.bz2 --directory /opt
          echo "PATH=/opt/avr-gcc-14.1.0-x64-linux/bin:$(echo $PATH)" >> $GITHUB_ENV
      - name: make
        run: |
          make
      - uses: actions/upload-artifact@v4
        with:
          name: beef-fw
          path: fw/beef.hex
          if-no-files-found: error

  utils:
    name: Build utils
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyinstaller

      - name: Package beef-tool
        run: |
          pyinstaller --onefile --noconsole --add-data "beef-tool/avrdude;avrdude" beef-tool/beef-tool.py

      - name: Prepare files for upload
        run: |
          mkdir -p tmp/beef-tool
          cp dist/beef-tool.exe tmp/beef-tool
          cp beef-tool/README.md tmp/beef-tool
          cp -r beef-tool/drivers tmp/beef-tool

          mkdir -p tmp/spiceapi
          cp -r spiceapi/* tmp/spiceapi

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: beef-utils
          path: |
            tmp/*

  beef-config:
    uses: ./.github/workflows/web-ci.yml
    with:
      upload_artifacts: false
